version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./.data/postgres:/data/postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    volumes:
      - ./.data/redis:/data/redis
    ports:
      - 6379:6379

  app:
    container_name: marketplace-backend
    image: marketplace-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis